# coding: utf-8

ss = [
    {
        "func_type":"嘴唇",   # 功能分类
        "position_icon_name":"唇厚",  # 功能名称
        "position_icon_before":"http://",   # 点击前icon 图
        "position_icon_after":"http://",        # 点击后icon 图
        "appeal_num":2,             # 诉求个数
        "default_value":50,     # 滑钮初始默认值
        "min_value":0,          # 滑钮调整数值前端外显区间 最小值
        "max_value":100,        # 滑钮调整数值前端外显区间 最大值
        "byte_type":"12",       # 字节形变功能(字节的功能编号)
        "slide_judge_standard":{
            ">50":{     # 滑钮数值判断标准
                "project_tag_name":[        # 精准商业标签
                    "玻尿酸丰唇",
                    "胶原蛋白填充丰唇",
                    "自体脂肪丰唇"
                ]
            },
            "<50":{     # 滑钮数值判断标准
                "project_tag_names":[       # 精准商业标签
                    "厚唇改薄术"
                ]
            }
        }
    },
    {
        "func_type":"嘴唇",
        "position_icon_name":"微笑唇",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"13",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "嘴角上扬术"
                ]
            }
        }
    },
    {
        "func_type":"嘴唇",
        "position_icon_name":"缩人中",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"16",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "人中缩短"
                ]
            }
        }
    },
    {
        "func_type":"眼部",
        "position_icon_name":"双眼皮",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":-1,
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "定点双眼皮",
                    "埋线双眼皮",
                    "切开双眼皮"
                ]
            }
        }
    },
    {
        "func_type":"眼部",
        "position_icon_name":"丰卧蚕",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":-1,
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "真皮填充卧蚕",
                    "卧蚕手术修复",
                    "玻尿酸填充卧蚕",
                    "自体脂肪填充卧蚕"
                ]
            }
        }
    },
    {
        "func_type":"眼部",
        "position_icon_name":"祛黑眼圈",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"17",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "射频祛黑眼圈",
                    "微针祛黑眼圈",
                    "激光祛黑眼圈",
                    "自体脂肪填充黑眼圈",
                    "玻尿酸祛黑眼圈",
                    "胶原蛋白填充祛黑眼圈"
                ]
            }
        }
    },
    {
        "func_type":"眼部",
        "position_icon_name":"开眼角",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"14",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "开外眼角"
                ]
            }
        }
    },
    {
        "func_type":"皮肤",
        "position_icon_name":"美白",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":-1,
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "小棕瓶美白",
                    "彩光嫩肤",
                    "镭射净肤",
                    "白瓷娃娃",
                    "光子嫩肤",
                    "黑脸娃娃",
                    "美白套餐",
                    "美白导入",
                    "皮秒激光"
                ]
            }
        }
    },
    {
        "func_type":"皮肤",
        "position_icon_name":"磨皮",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":-1,
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "彩光嫩肤",
                    "镭射净肤",
                    "白瓷娃娃",
                    "光子嫩肤",
                    "黑脸娃娃",
                    "皮秒激光",
                    "小气泡美肤",
                    "激光祛斑"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"瘦脸",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"2",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "注射瘦脸",
                    "光纤溶脂瘦脸",
                    "射频溶脂瘦脸",
                    "取颊脂垫瘦脸",
                    "激光溶脂瘦脸",
                    "溶脂针瘦脸"
                ]
            },
            "<50":{
                "project_tag_names":[
                    "自体脂肪全面部填充",
                    "自体脂肪丰面颊",
                    "玻尿酸丰面颊"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"祛法令纹",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"18",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "玻尿酸除法令纹",
                    "注射祛法令纹",
                    "胶原蛋白填充除法令纹",
                    "自体脂肪除法令纹",
                    "热拉提",
                    "热玛吉"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"垫下巴",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"10",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "玻尿酸丰下巴",
                    "胶原蛋白填充丰下巴",
                    "自体脂肪丰下巴",
                    "膨体垫下巴",
                    "硅胶垫下巴"
                ]
            },
            "<50":{
                "project_tag_names":[
                    "缩下巴"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"瘦颧骨",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":1,
        "default_value":0,
        "min_value":0,
        "max_value":100,
        "byte_type":"6",
        "slide_judge_standard":{
            ">0":{
                "project_tag_name":[
                    "颧骨内推",
                    "颧骨颧弓整形术"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"瘦下颌",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"7",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "注射瘦脸",
                    "光纤溶脂瘦脸",
                    "射频溶脂瘦脸",
                    "取颊脂垫瘦脸",
                    "激光溶脂瘦脸",
                    "溶脂针瘦脸",
                    "下颌角整形",
                    "下颌角切除术"
                ]
            },
            "<50":{
                "project_tag_names":[
                    "自体脂肪全面部填充"
                ]
            }
        }
    },
    {
        "func_type":"轮廓",
        "position_icon_name":"丰额头",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"11",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "硅胶丰额头",
                    "膨体丰额头",
                    "玻尿酸丰额头",
                    "胶原蛋白填充额头",
                    "自体脂肪丰额头"
                ]
            },
            "<50":{
                "project_tag_names":[
                    "额头缩小"
                ]
            }
        }
    },
    {
        "func_type":"鼻子",
        "position_icon_name":"缩鼻翼",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"8",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "鼻翼缩小"
                ]
            },
            "<50":{
                "project_tag_names":[

                ]
            }
        }
    },
    {
        "func_type":"鼻部",
        "position_icon_name":"鼻尖",
        "position_icon_before":"http://",
        "position_icon_after":"http://",
        "appeal_num":2,
        "default_value":50,
        "min_value":0,
        "max_value":100,
        "byte_type":"9",
        "slide_judge_standard":{
            ">50":{
                "project_tag_name":[
                    "鼻小柱缩短",
                    "耳软骨隆鼻",
                    "鼻中隔软骨隆鼻",
                    "硅胶隆鼻",
                    "膨体隆鼻",
                    "鼻中隔软骨垫鼻头"
                ]
            },
            "<50":{
                "project_tag_names":[
                    "鼻小柱延长"
                ]
            }
        }
    }
]


from typing import List


class Solution:
    def search(self, nums: List[int], target: int) -> int:
        pass
